version: "2"
services:
  db:
    build:
      context: containers/db
      dockerfile: Dockerfile_x64
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    volumes:
      - ./data/db:/var/lib/mysql
      - ./hooks:/hooks
    environment:
      MYSQL_ROOT_PASSWORD: absolutly_not_safe
      MYSQL_DATABASE: karambol
      MYSQL_USER: karambol
      MYSQL_PASSWORD: karambol
  web:
    build:
      context: containers/web
      dockerfile: Dockerfile_x64
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - KARAMBOL_REPOSITORY=https://github.com/Bornholm/karambol.git
        - KARAMBOL_TAG=develop
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: karambol
      MYSQL_USER: karambol
      MYSQL_PASSWORD: karambol
      KARAMBOL_ADMIN_USER: admin
      KARAMBOL_ADMIN_PASSWORD: not_safe_either
      STARTUP_HOOKS: /hooks/zoco
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    volumes:
      - ./hooks:/hooks
    ports:
      - 8888:80
    links:
      - db
