version: "2"
services:
  web:
    build:
      dockerfile: Dockerfile_zoco
      args:
        ZOCO_PLUGIN_VERSION: dev-develop
    volumes:
      - ./data/web/data:/opt/karambol/data
    links:
      - elasticsearch
    depends_on:
      - db
      - elasticsearch
  elasticsearch:
    build:
      context: ./containers/elasticsearch
      dockerfile: Dockerfile
      args:
          - HTTP_PROXY=${HTTP_PROXY}
          - HTTPS_PROXY=${HTTPS_PROXY}
          - http_proxy=${http_proxy}
          - https_proxy=${https_proxy}
    volumes:
      - ./data/elasticsearch:/var/elasticsearch
    ports:
      - 9200:9200
